---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/hw8_citibike1/hw8_citibike1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/249529/articles/335791/master/file/figures/hw8_citibike1/hw8_citibike1.png"
    folder_url: "/users/249529/articles/335791/master/folder/figures/hw8_citibike1"
